version: '3'

services:
  server:
    container_name: server
    restart: always
    build: ./docker-server
    ports:
      - "8001:8001"
    volumes:
      - ./docker-server:/usr/src/app
      - ./node_modules:/usr/src/app/node_modules
    depends_on:
      - postgres
  client:
    container_name: client
    restart: always
    build: ./docker-client
    ports:
      - "8000:8000"
    volumes:
      - ./docker-client:/usr/src/app
      - ./node_modules:/usr/src/app/node_modules
    depends_on:
      - redis
  postgres:
      container_name: postgres
      image: 'bitnami/postgresql:latest'
      restart: always
      environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
        - POSTGRESQL_DATABASE=tarea1
      ports:
        - '5438:5432'
      volumes: 
        - ./data.sql:/docker-entrypoint-initdb.d/create_tables.sql
  redis:
      container_name: redis
      image: 'bitnami/redis:latest'
      restart: always
      ports:
        - '6379:6379'
      environment:
        - ALLOW_EMPTY_PASSWORD=yes
      volumes:
        - ./redis.conf:/usr/local/etc/redis/redis.conf 

