version: '3'

services:
  server:
    container_name: server
    build: ./docker-server
    ports:
      - "8001:8001"
    depends_on:
      - postgres
  client:
    container_name: client
    build: ./docker-client
    ports:
      - "8000:8000"
    depends_on:
      - redis
  postgres:
      container_name: postgres
      image: 'bitnami/postgresql:latest'
      environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
        - POSTGRESQL_DATABASE=tarea1
      ports:
        - '5438:5432'
      volumes: 
        - ./data.sql:/docker-entrypoint-initdb.d/create_tables.sql
  redis:
      container_name: redis
      image: 'bitnami/redis:latest'
      ports:
        - '6379:6379'
      environment:
        - ALLOW_EMPTY_PASSWORD=yes
      command: /opt/bitnami/scripts/redis/run.sh --maxmemory 50mb --maxmemory-policy allkeys-lfu


