version: '3'

services:
  web:
    container_name: api
    restart: always
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/usr/src/app
    depends_on:
      - postgres
      - redis
  postgres:
      image: 'bitnami/postgresql:latest'
      restart: always
      environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
        - POSTGRESQL_DATABASE=tarea1
      ports:
        - '5438:5432'
      volumes: 
        - ./data.sql:/docker-entrypoint-initdb.d/create_tables.sql
  redis:
      image: 'bitnami/redis:latest'
      restart: always
      ports:
        - '6379:6379'
      environment:
        - ALLOW_EMPTY_PASSWORD=yes

