version: "3"
services:

  producer:
    container_name: producer
    build: ./docker-producer
    ports:
      - "8000:8000"
    depends_on:
      - kafka
  consumer:
    container_name: consumer
    build: ./docker-consumer
    volumes:
      - ./docker-consumer/block.json:/usr/src/app/block.json
    ports:
      - "8001:8001"
    depends_on:
      - kafka
  zookeeper:
    image: 'bitnami/zookeeper:latest'
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka:
    image: 'bitnami/kafka:latest'
    ports:
      - '9092:9092'
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper
  postgres:
      container_name: postgres
      image: 'bitnami/postgresql:latest'
      environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
        - POSTGRESQL_DATABASE=tarea2
      ports:
        - '5438:5432'
      volumes: 
        - ./data.sql:/docker-entrypoint-initdb.d/create_tables.sql